# Generated by Django 5.1.4 on 2025-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reporting_user', models.GenericIPAddressField()),
                ('reported_user', models.GenericIPAddressField()),
                ('reported_data', models.TextField()),
                ('moderator_verdict', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=100)),
                ('verdict_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_note', models.TextField(blank=True)),
            ],
        ),
    ]
