# Generated by Django 5.1.4 on 2025-07-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
    ]
