# Generated by Django 5.1.4 on 2025-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_report_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('person_email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
